name: home-library-service

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    depends_on:
      - postgres
    ports:
      - 4000:4000
    restart: always

  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=Rukala
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

networks:
  my-bridge:
    driver: bridge

volumes:
  postgres: